version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(deps-dev)"
  - package-ecosystem: npm
    directory: /mappe
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(mappe)"
